<?php
	
	//Funcion para que dibuje el login sin menu
	function dibuja0(){
		include('../aspecto/sinMenu.html');
		echo '<br>';echo '<br>';
		include('../aspecto/pie.html');
		
	}
		
	function dibuja(){
		include('./aspecto/sinMenu.html');
		echo '<br>';echo '<br>';
		include('./aspecto/pie.html');
	}
	
	function dibuja2(){
		include('./aspecto/menu.html');
		echo '<br>';echo '<br>';
		include('./aspecto/pie.html');
	}	
	
	function dibuja1(){
		include('../../aspecto/menu.html');
		echo '<br>';echo '<br>';
		include('../../aspecto/pie.html');


	}	
	
?> 